version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./app/backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin1234
      - DB_NAME=tododb
    depends_on:
      - db
  frontend:
    build: 
      context: ./app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend