services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root # ต้องใช้ root เพื่อให้ Jenkins สั่งงาน Docker ของเครื่องเราได้
    ports:
      - "8080:8080" # หน้าเว็บ Jenkins จะเข้าผ่านพอร์ตนี้
    volumes:
      - jenkins_home:/var/jenkins_home
      # บรรทัดนี้สำคัญมาก! คือการเจาะท่อให้ Jenkins สั่งงาน Docker เครื่องหลักได้
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: