apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: frontend
        image: pawit44/todo-frontend:latest
        ports:
        - containerPort: 3000
      - name: backend
        image: pawit44/todo-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER       # เพิ่มเข้ามา
          value: "postgres"
        - name: DB_PASSWORD   # เพิ่มเข้ามา
          value: "admin1234"
        - name: DB_NAME       # เพิ่มเข้ามา
          value: "tododb" 